version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    hostname: api-gateway
    restart: on-failure
    ports:
      - "8080:8080"
    logging:
      driver: none
    networks:
      - network
      
university-service:
    image: university-service
    build:
      context: .
      dockerfile: university-service/Dockerfile
    restart: always
    container_name: "university-service"
    hostname: "university-service"
    environment:
      - PORT=8080
    networks:
      - network
    depends_on:
      - university-service-db
      
university-service-db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
      # Docker healtcheck - checks if database is "alive"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - university-service-db_store:/data/db
    networks:
      - network

networks:
  network:
    driver: bridge
