version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    hostname: api-gateway
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - university-service
      - dorm-service
      - healthcare-service
    logging:
      driver: none
    networks:
      - network

  university-service:
    image: university-service
    build:
      context: .
      dockerfile: university-service/Dockerfile
    restart: always
    container_name: "university-service"
    hostname: "university-service"
    environment:
      - PORT=${UNIVERSITY_SERVICE_PORT}
      - UNIVERSITY_MONGO_URI=${UNIVERSITY_MONGO_URI}
      - HEALTHCARE_SERVICE_PORT=${HEALTHCARE_SERVICE_PORT}
      - HEALTHCARE_SERVICE_URL=${HEALTHCARE_SERVICE_URL}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    networks:
      - network
    depends_on:
      - university-service-db

  university-service-db:
    image: mongo
    restart: always
    ports:
      - "27021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
      # Docker healtcheck - checks if database is "alive"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - university-service-db_store:/data/db
    networks:
      - network
    depends_on:
      - auth-service
      - healthcare-service

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    image: auth-service
    container_name: auth-service
    restart: always
    hostname: "auth-server"
    depends_on:
      - auth-db
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - AUTH_MONGO_URI=${AUTH_MONGO_URI}
      - JWT_KEY=${JWT_KEY}
    networks:
      - network

  auth-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
      ME_CONFIG_MONGODB_SERVER: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - auth-db_store:/data/db
    networks:
      - network

  food-service:
    build:
      context: .
      dockerfile: ./food-service/Dockerfile
    image: food-service
    container_name: food-service
    restart: always
    hostname: "food-server"
    depends_on:
      - food-db
    environment:
      - PORT=${FOOD_SERVICE_PORT}
      - FOOD_MONGO_URI=${FOOD_MONGO_URI}
      - UNIVERSITY_SERVICE_URL=${UNIVERSITY_SERVICE_URL}
      - UNIVERSITY_SERVICE_PORT=${UNIVERSITY_SERVICE_PORT}
    networks:
      - network

  food-db:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - food-db_store:/data/db
    networks:
      - network

  healthcare-service:
    build:
      context: .
      dockerfile: ./healthcare-service/Dockerfile
    image: healthcare-service
    container_name: healthcare-service
    restart: always
    hostname: "healthcare-server"
    depends_on:
      - healthcare-db
    environment:
      - PORT=${HEALTHCARE_SERVICE_PORT}
      - HEALTHCARE_MONGO_URI=${HEALTHCARE_MONGO_URI}
    networks:
      - network

  healthcare-db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - healthcare-db_store:/data/db
    networks:
      - network

  dorm-db:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
      ME_CONFIG_MONGODB_SERVER: mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - dorm-db_store:/data/db
    networks:
      - network

  dorm-service:
    build:
      context: .
      dockerfile: ./dorm-service/Dockerfile
    image: dorm-service
    container_name: dorm-service
    restart: always
    hostname: "dorm-server"
    depends_on:
      - dorm-db
    environment:
      - PORT=${DORM_PORT}
      - DORM_MONGO_URI=${DORM_MONGO_URI}
      - HEALTHCARE_SERVICE_URL=${HEALTHCARE_SERVICE_URL}
      - HEALTHCARE_SERVICE_PORT=${HEALTHCARE_SERVICE_PORT}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - UNIVERSITY_SERVICE_URL=${UNIVERSITY_SERVICE_URL}
      - UNIVERSITY_SERVICE_PORT=${UNIVERSITY_SERVICE_PORT}
    networks:
      - network
networks:
  network:
    driver: bridge

volumes:
  university-service-db_store:
  auth-db_store:
  food-db_store:
  healthcare-db_store:
  dorm-db_store:
